# Generated by Django 5.0.6 on 2024-09-05 09:53

import django_ckeditor_5.fields
import django.db.models.deletion
import imagekit.models.fields
import product.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_reason', models.CharField(blank=True, max_length=250, null=True, verbose_name='علت عدم تایید')),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات متا')),
                ('meta_keywords', models.TextField(blank=True, max_length=250, null=True, verbose_name='کلمات کلیدی')),
                ('status', models.IntegerField(choices=[(1, 'در انتظار بررسی'), (2, 'رفع ایراد'), (3, 'رد شده'), (4, 'تایید شده')], default=1, verbose_name='وضعیت تایید')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان برند')),
                ('display_order', models.IntegerField(default=2, verbose_name='اولویت نمایش')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path_brand, verbose_name='تصویر شاخص')),
                ('image_webp', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path_brand, verbose_name='تصویر شاخص وب')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('shortDescription', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات کوتاه')),
                ('Description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات اصلی')),
                ('canonical', models.URLField(blank=True, null=True, verbose_name='لینک کنونیکال')),
                ('create_link_allowed', models.BooleanField(default=True, verbose_name='وضعیت ساخت لینک داخلی')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='صفحه noindex شود')),
                ('http_response_gone', models.BooleanField(default=False, verbose_name='410 شود')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductsCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('meta_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات سئو')),
                ('keywords', models.TextField(blank=True, max_length=250, null=True, verbose_name='کلمات کلیدی')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path, verbose_name='تصویر شاخص')),
                ('image_webp', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path, verbose_name='تصویر شاخص وب')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('depth', models.IntegerField(default=1, null=True, verbose_name='عمق گروه')),
                ('Display_order', models.IntegerField(default=1, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('canonical', models.URLField(blank=True, null=True, verbose_name='لینک کنونیکال')),
                ('create_link_allowed', models.BooleanField(default=True, verbose_name='وضعیت ساخت لینک داخلی')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='صفحه noindex شود')),
                ('http_response_gone', models.BooleanField(default=False, verbose_name='410 شود')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='product.productscats', verbose_name='دسته بندی مادر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی محصولات',
                'ordering': ['Display_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='این فیلد نباید خالی باشد و تعداد کارکترهای آن باید بیشتر از 150 کاراکتر نباشند', max_length=600, verbose_name='عنوان')),
                ('en_title', models.CharField(blank=True, max_length=600, null=True, verbose_name='نام انگلیسی محصول')),
                ('unit', models.CharField(default='دستگاه', max_length=250, verbose_name='واحد شمارشی محصول')),
                ('meta_title', models.CharField(blank=True, max_length=600, null=True, verbose_name='عنوان سئو')),
                ('meta_desc', models.CharField(blank=True, max_length=600, null=True, verbose_name='توضیحات سئو')),
                ('keywords', models.TextField(blank=True, max_length=600, null=True, verbose_name='کلمات کلیدی')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='نام در url')),
                ('Description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات اصلی')),
                ('shortDescription', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات کوتاه')),
                ('weight', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='وزن محصول')),
                ('depth', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='طول')),
                ('height', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='ارتفاع')),
                ('width', models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='عرض')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path, verbose_name='تصویر شاخص')),
                ('image_webp', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path, verbose_name='لینک تصویر')),
                ('image_200', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path_200, verbose_name='لینک تصویر 200 ')),
                ('image_webp_200', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path_200, verbose_name='لینک تصویر وب 200')),
                ('image_300', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path_300, verbose_name='لینک تصویر 300')),
                ('image_webp_300', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path_300, verbose_name='لینک تصویر وب 300')),
                ('image_500', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path_500, verbose_name='لینک تصویر 500')),
                ('image_webp_500', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path_500, verbose_name='لینک تصویر وب 500')),
                ('image_alt', models.CharField(blank=True, max_length=500, null=True, verbose_name='عنوان تصویر')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('dkp_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='سناسه محصول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='لینک ویدئوی محصول')),
                ('review_reason', models.CharField(blank=True, max_length=250, null=True, verbose_name='علت عدم تایید')),
                ('canonical', models.URLField(blank=True, null=True, verbose_name='لینک کنونیکال')),
                ('create_link_allowed', models.BooleanField(default=True, verbose_name='وضعیت ساخت لینک داخلی')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='صفحه noindex شود')),
                ('http_response_gone', models.BooleanField(default=False, verbose_name='410 شود')),
                ('brandId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brand', verbose_name='برند')),
                ('similar_products', models.ManyToManyField(blank=True, to='product.product', verbose_name='محصولات مشابه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('RootCategoryId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productscats', verbose_name='دسته بندی اصلی')),
                ('otherCategories', models.ManyToManyField(blank=True, related_name='otherCategories', to='product.productscats', verbose_name='دسته های دیگر')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
