# Generated by Django 5.0.6 on 2024-09-05 12:50

import django.db.models.deletion
import imagekit.models.fields
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(default='کیلوگرم', max_length=250, verbose_name='واحد شمارشی محصول'),
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path, verbose_name='لینک تصویر jpeg')),
                ('image_webp', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path, verbose_name='لینک تصویر webp')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='عنوان محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
            },
        ),
    ]
