# Generated by Django 5.0.6 on 2024-09-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_depth_remove_product_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='status',
        ),
    ]
