# Generated by Django 5.0.6 on 2024-09-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_brand_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shortDescription',
        ),
    ]
