# Generated by Django 5.0.6 on 2024-09-05 16:58

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_shortdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('type', models.IntegerField(choices=[(1, 'متنی'), (2, 'تصویری'), (3, 'رنگ')], default=1, verbose_name='نوع')),
                ('display_order', models.IntegerField(default=1, verbose_name='اولویت نمایش')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگیها',
            },
        ),
        migrations.CreateModel(
            name='AttributeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(verbose_name='مقدار')),
                ('display_order', models.IntegerField(default=1, verbose_name='اولویت نمایش')),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.upload_image_path, verbose_name='تصویر')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.attribute', verbose_name='ویژگی')),
            ],
            options={
                'verbose_name': 'مقدارویژگی',
                'verbose_name_plural': 'مقادیر ویژگیها',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_as_variant', models.BooleanField(default=False, verbose_name='اسفتاده تنوع')),
                ('display_order', models.IntegerField(default=1, verbose_name='اولویت نمایش')),
                ('attributeItem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.attributeitem', verbose_name='مقدار ویژگی')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی های محصول',
                'ordering': ['-id'],
            },
        ),
    ]
