# Generated by Django 5.0.6 on 2024-09-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_attribute_attributeitem_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='usa_as_variant',
        ),
    ]
