# Generated by Django 5.0.6 on 2024-09-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_productattribute_usa_as_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='type',
        ),
    ]
