# Generated by Django 5.0.6 on 2024-09-06 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_attribute_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0, verbose_name='وزن')),
                ('quantity', models.IntegerField(default=0, verbose_name='موجودی')),
                ('delivery_time', models.PositiveSmallIntegerField(default=1, verbose_name='زمان تحویل این محصول(روز)')),
                ('regular_price', models.FloatField(default=0, verbose_name='قیمت عادی')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت نمایش')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تنوع محصول',
                'verbose_name_plural': 'تنوع های محصول',
            },
        ),
    ]
