# Generated by Django 5.0.6 on 2024-09-06 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_othercategories_productfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='RootCategoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productscats', verbose_name='دسته بندی'),
        ),
    ]
