# Generated by Django 5.0.6 on 2024-09-13 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_rootcategoryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMainFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=150, verbose_name='مشخصه')),
                ('feature_value', models.CharField(max_length=150, verbose_name='مقدار')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='عنوان محصول')),
            ],
            options={
                'verbose_name': 'مشخصه اصلی',
                'verbose_name_plural': 'مشخصات اصلی محصول',
                'ordering': ('-id',),
            },
        ),
    ]
