# Generated by Django 5.0.6 on 2024-09-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productmainfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='in_basket',
            field=models.IntegerField(default=0, verbose_name='محدودیت تعداد در سبد'),
        ),
    ]
