# Generated by Django 5.0.6 on 2024-09-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productinventory_in_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='supplement_price',
            field=models.FloatField(default=0, verbose_name='قیمت تامین'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='regular_price',
            field=models.FloatField(default=0, verbose_name='قیمت فروش'),
        ),
    ]
