# Generated by Django 5.0.6 on 2024-09-29 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productinventory_supplement_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان گروه')),
                ('display_order', models.IntegerField(default=1, verbose_name='اولویت نمایش')),
            ],
            options={
                'verbose_name': 'گروه ویژگی',
                'verbose_name_plural': 'گروه های ویژگی',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='group_attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.groupattribute', verbose_name='گروه ویژگی'),
            preserve_default=False,
        ),
    ]
