# Generated by Django 5.0.6 on 2024-09-29 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_groupattribute_attribute_group_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='حالت')),
            ],
            options={
                'verbose_name': 'حالت کالا',
                'verbose_name_plural': 'حالتها کالا',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'واحد اندازه گیری',
                'verbose_name_plural': 'واحد های اندازه گیری',
            },
        ),
        migrations.AddField(
            model_name='productinventory',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.shape', verbose_name='حالت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.units', verbose_name='واحد شمارشی محصول'),
        ),
    ]
