# Generated by Django 5.0.6 on 2024-09-29 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_shape_units_productinventory_shape_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='shape',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.units', verbose_name='واحد اندازه گیری'),
        ),
        migrations.DeleteModel(
            name='Shape',
        ),
    ]
