# Generated by Django 5.0.6 on 2024-09-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_productinventory_shape_alter_product_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='supplement_price',
        ),
        migrations.AddField(
            model_name='productinventory',
            name='unit',
            field=models.FloatField(default=0, verbose_name='هر واحد برابر استب با'),
        ),
    ]
