# Generated by Django 5.0.6 on 2024-09-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_productinventory_supplement_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinventory',
            name='unit',
        ),
    ]
