# Generated by Django 5.0.6 on 2024-09-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_productinventory_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='unit',
            field=models.FloatField(default=0, verbose_name='هر واحد برابر استب با'),
        ),
    ]
