# Generated by Django 5.0.6 on 2024-09-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productinventory_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='title',
            field=models.CharField(default='125', max_length=150, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
