# Generated by Django 5.0.6 on 2024-10-01 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_productinventory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='unit',
            field=models.FloatField(default=0, verbose_name='هر واحد برابر است با'),
        ),
        migrations.CreateModel(
            name='AttributeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان فیلتر')),
                ('display_order', models.IntegerField(default=1, verbose_name='الویت نمایش')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attribute', verbose_name='ویژگی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productscats', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'فیلتر دسته بندی',
                'verbose_name_plural': 'فیلترهای دسته بندی',
            },
        ),
    ]
