# Generated by Django 5.0.6 on 2024-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_productinventory_unit_attributefilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='supplement_price',
            field=models.FloatField(default=0, verbose_name='قیمت تامین'),
        ),
    ]
