# Generated by Django 5.0.6 on 2024-10-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_productinventory_supplement_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان'),
        ),
    ]
