# Generated by Django 5.0.6 on 2024-10-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_productinventory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscats',
            name='for_display_in_slider',
            field=models.BooleanField(default=False, verbose_name='نمایش در اسلایدر دسته بندی ها'),
        ),
    ]
