# Generated by Django 5.0.6 on 2024-10-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_productscats_for_display_in_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductExperts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('position', models.CharField(max_length=150, verbose_name='سمت')),
                ('whatsapp_number', models.CharField(max_length=11, verbose_name='شماره واتس اپ')),
                ('phone_number', models.CharField(max_length=50, verbose_name='شماره تماس')),
            ],
            options={
                'verbose_name': 'کارشناس محصول',
                'verbose_name_plural': 'کارشناسان محصول',
            },
        ),
    ]
