# Generated by Django 5.0.6 on 2024-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_productexperts'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscats',
            name='experts',
            field=models.ManyToManyField(blank=True, null=True, to='product.productexperts', verbose_name='کارشناسان این دسته بندی'),
        ),
    ]
