# Generated by Django 5.0.6 on 2024-10-09 12:55

import imagekit.models.fields
import product.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_productscats_experts'),
    ]

    operations = [
        migrations.AddField(
            model_name='productexperts',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=product.models.upload_image_path, verbose_name='تصویر کارشناس'),
        ),
    ]
