# Generated by Django 5.0.6 on 2024-10-09 13:00

import imagekit.models.fields
import product.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_productexperts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productexperts',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=product.models.upload_image_path, verbose_name='تصویر کارشناس'),
        ),
    ]
