# Generated by Django 5.0.6 on 2024-10-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_alter_productexperts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_200',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_300',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_500',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_webp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_webp_200',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_webp_300',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_webp_500',
        ),
    ]
