# Generated by Django 5.0.6 on 2024-10-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_product_image_200_remove_product_image_300_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='image_webp',
        ),
        migrations.RemoveField(
            model_name='productscats',
            name='image_webp',
        ),
    ]
