# Generated by Django 5.0.6 on 2024-10-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_remove_brand_image_webp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscats',
            name='experts',
            field=models.ManyToManyField(to='product.productexperts', verbose_name='کارشناسان این دسته بندی'),
        ),
    ]
