# Generated by Django 5.0.6 on 2024-11-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_productscats_experts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='image_webp',
        ),
    ]
