# Generated by Django 5.0.6 on 2024-11-16 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_remove_productgallery_image_webp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinventory',
            name='after_discount',
            field=models.FloatField(default=0, verbose_name='قیمت بعد از کسر تخفیف'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='on_sale_from',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='ویژه از تاریخ'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='on_sale_to',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='ویژه تا تاریخ'),
        ),
        migrations.AddField(
            model_name='productinventory',
            name='price',
            field=models.FloatField(default=0, verbose_name='قیمت اعمال شده'),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='regular_price',
            field=models.FloatField(default=0, verbose_name='قیمت عادی'),
        ),
    ]
