# Generated by Django 5.0.6 on 2024-12-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_productinventory_after_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventory',
            options={'ordering': ['thickness'], 'verbose_name': 'تنوع محصول', 'verbose_name_plural': 'تنوع های محصول'},
        ),
        migrations.AddField(
            model_name='productinventory',
            name='thickness',
            field=models.IntegerField(default=0, verbose_name='ضخامت'),
        ),
    ]
