# Generated by Django 5.0.6 on 2024-12-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_productinventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='thickness',
            field=models.FloatField(default=0, verbose_name='ضخامت'),
        ),
    ]
