# Generated by Django 5.0.6 on 2025-03-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_productinventory_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='in_basket',
            field=models.IntegerField(default=1, verbose_name='محدودیت تعداد در سبد'),
        ),
    ]
