# Generated by Django 5.0.6 on 2025-06-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_productinventory_in_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='create_link_allowed',
            field=models.BooleanField(default=False, verbose_name='وضعیت ساخت لینک داخلی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_link_allowed',
            field=models.BooleanField(default=False, verbose_name='وضعیت ساخت لینک داخلی'),
        ),
        migrations.AlterField(
            model_name='productscats',
            name='create_link_allowed',
            field=models.BooleanField(default=False, verbose_name='وضعیت ساخت لینک داخلی'),
        ),
    ]
