# Generated by Django 5.0.6 on 2024-10-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'عنوان تماس با ما',
                'verbose_name_plural': 'عناوین تماس با ما',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=250, verbose_name='عنوان'),
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name=' نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=250, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=250, verbose_name='آدرس ایمیل')),
                ('text', models.TextField(verbose_name='من درخواست')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.contactsubject', verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماسها',
            },
        ),
    ]
