# Generated by Django 5.0.6 on 2024-10-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactsubject_alter_page_title_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان ثبت تماس'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت تماس'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='من درخواست'),
        ),
    ]
