# Generated by Django 5.0.6 on 2024-10-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_remove_menulist_page'),
        ('pages', '0003_contactus_date_contactus_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
