# Generated by Django 5.0.6 on 2024-10-08 12:46

import django_ckeditor_5.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_delete_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'در انتظار بررسی'), (2, 'رفع ایراد'), (3, 'رد شده'), (4, 'تایید شده')], default=1, verbose_name='وضعیت تایید')),
                ('review_reason', models.CharField(blank=True, max_length=250, null=True, verbose_name='علت عدم تایید')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='نام در url')),
                ('meta_desc', models.CharField(blank=True, max_length=156, null=True, verbose_name='توضیحات متا')),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True, verbose_name='عنوان سئو')),
                ('keywords', models.CharField(max_length=150, verbose_name='کلمات کلیدی')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='توضیحات اصلی')),
                ('content_jinja', models.TextField(blank=True, null=True, verbose_name='کدهای html پویا')),
                ('use_content_jinja', models.BooleanField(default=False, verbose_name='استفاده از کدهای html پویا در صفحه')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('canonical', models.URLField(blank=True, null=True, verbose_name='لینک کنونیکال')),
                ('create_link_allowed', models.BooleanField(default=True, verbose_name='وضعیت ساخت لینک داخلی')),
                ('http_response_gone', models.BooleanField(default=False, verbose_name='410 شود')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='صفحه noindex شود')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'برگه',
                'verbose_name_plural': 'برگه ها',
            },
        ),
    ]
