# Generated by Django 5.0.6 on 2024-10-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='create_link_allowed',
        ),
    ]
