# Generated by Django 5.0.6 on 2024-10-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_page_create_link_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_main_page',
            field=models.BooleanField(default=False, verbose_name='محتوای صفحه اصلی سایت'),
        ),
    ]
