# Generated by Django 5.0.6 on 2024-10-09 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_is_main_page'),
        ('product', '0024_productscats_for_display_in_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='آدرس ایمیل')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='زمان ثبت تماس')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ایمیل',
                'verbose_name_plural': 'ایمیلهای خبر نامه',
            },
        ),
    ]
