# Generated by Django 5.0.6 on 2024-10-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='product',
        ),
    ]
