# Generated by Django 5.0.6 on 2025-04-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_emails_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(default=1, max_length=250, verbose_name='آدرس ایمیل'),
            preserve_default=False,
        ),
    ]
