# Generated by Django 5.0.6 on 2025-06-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_emails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='create_link_allowed',
            field=models.BooleanField(default=False, verbose_name='وضعیت ساخت لینک داخلی'),
        ),
    ]
