# Generated by Django 5.0.6 on 2025-07-05 06:55

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_page_create_link_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='توضیحات اصلی'),
        ),
    ]
