# Generated by Django 5.0.6 on 2025-07-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='slug',
            field=models.SlugField(help_text='در ابرازکها جهت فراخوانی فرم استفاده می شود', null=True, verbose_name='نامک'),
        ),
    ]
