# Generated by Django 5.0.6 on 2025-07-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_contactus_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='is_english_form',
            field=models.BooleanField(default=False, verbose_name='فرم انگلیسی است'),
        ),
    ]
