# Generated by Django 5.0.6 on 2025-07-06 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_contactus_is_english_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='این فیلد نباید خالی باشد و تعداد کارکترهای آن باید بیشتر از 150 کاراکتر نباشند', max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(help_text='در ابرازکها جهت فراخوانی فرم استفاده می شود', null=True, verbose_name='نامک')),
                ('is_english_form', models.BooleanField(default=False, verbose_name='فرم انگلیسی است')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'فرم تماس',
                'verbose_name_plural': 'فرم های تماس',
            },
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='is_english_form',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='slug',
        ),
        migrations.AddField(
            model_name='contactsubject',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.contact', verbose_name='فرم'),
        ),
    ]
