# Generated by Django 5.0.6 on 2025-07-06 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_contact_remove_contactus_is_english_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='use_content_jinja',
        ),
        migrations.AddField(
            model_name='page',
            name='contact_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.contact', verbose_name='فرم تماس'),
        ),
    ]
