# Generated by Django 5.0.6 on 2024-10-07 10:27

import blog.models
import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='عنوان در url')),
                ('timstamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسبها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'در انتظار بررسی'), (2, 'رفع ایراد'), (3, 'رد شده'), (4, 'تایید شده')], default=1, verbose_name='وضعیت تایید')),
                ('review_reason', models.CharField(blank=True, max_length=250, null=True, verbose_name='علت عدم تایید')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان سئو')),
                ('meta_desc', models.TextField(blank=True, max_length=250, null=True, verbose_name='توضیحات سئو')),
                ('keywords', models.TextField(blank=True, max_length=150, null=True, verbose_name='کلمات کلیدی')),
                ('slug', models.SlugField(unique=True, verbose_name='نام در url')),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات اصلی')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=blog.models.upload_image_path, verbose_name='تصویر شاخص')),
                ('image_webp', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=blog.models.upload_image_path, verbose_name='لینک تصویر')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('canonical', models.URLField(blank=True, null=True, verbose_name='لینک کنونیکال')),
                ('create_link_allowed', models.BooleanField(default=True, verbose_name='وضعیت ساخت لینک داخلی')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='صفحه noindex شود')),
                ('http_response_gone', models.BooleanField(default=False, verbose_name='410 شود')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'نوشته',
                'verbose_name_plural': 'نوشته ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500, verbose_name='متن نظرسنجی')),
                ('post_type', models.CharField(choices=[('2', 'نوشته ها')], max_length=2, verbose_name='نوع پست')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نظرسنجی')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='وضعیت تایید')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='عنوان کاربر')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='عنوان پست')),
            ],
            options={
                'verbose_name': 'نظر در مورد پست',
                'verbose_name_plural': 'نظرات در مورد پست ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان سئو')),
                ('meta_description', models.TextField(blank=True, max_length=150, null=True, verbose_name='توضیحات سئو')),
                ('keywords', models.TextField(blank=True, max_length=150, null=True, verbose_name='کلمات کلیدی')),
                ('slug', models.SlugField(unique=True, verbose_name='عنوان در url')),
                ('display_order', models.IntegerField(default=1, verbose_name='اولویت نمایش')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روز رسانی')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=blog.models.upload_image_path, verbose_name='تصویر شاخص')),
                ('image_webp', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=blog.models.upload_image_path, verbose_name='لینک تصویر')),
                ('canonical', models.URLField(blank=True, null=True, verbose_name='لینک کنونیکال')),
                ('is_noindex', models.BooleanField(default=False, verbose_name='صفحه noindex شود')),
                ('http_response_gone', models.BooleanField(default=False, verbose_name='410 شود')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.postcategory', verbose_name='دسته بندی مادر')),
            ],
            options={
                'verbose_name': 'دسته بندی نوشته',
                'verbose_name_plural': 'دسته بندی نوشته ها',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.postcategory', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='برچسبها'),
        ),
    ]
