# Generated by Django 5.0.6 on 2024-10-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='parent',
        ),
    ]
