# Generated by Django 5.0.6 on 2024-10-12 09:12

import blog.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_postcategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_webp',
        ),
        migrations.RemoveField(
            model_name='postcategory',
            name='image_webp',
        ),
        migrations.AlterField(
            model_name='postcategory',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='طول 1284 و عرض 600 پیکسل باشد', null=True, upload_to=blog.models.upload_image_path, verbose_name='تصویر شاخص'),
        ),
    ]
