# Generated by Django 5.0.6 on 2025-04-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_image_webp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='متن پاسخ')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ نظرسنجی')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comments', verbose_name='پاسخ')),
            ],
        ),
    ]
