# Generated by Django 5.0.6 on 2025-04-27 11:14

import blog.models
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_commentreply_options'),
        ('product', '0036_alter_productinventory_in_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default=1, max_length=250, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='عنوان محصول'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumb_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=blog.models.upload_image_path, verbose_name='تصویر بند انگشتی'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_type',
            field=models.CharField(choices=[('2', 'نوشته ها'), ('3', 'محصولات')], max_length=2, verbose_name='نوع پست'),
        ),
    ]
