# Generated by Django 5.0.6 on 2025-04-27 12:05

import blog.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comments_name_comments_product_post_thumb_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='ابعاد تصویر 1284 عرض در 600 ارتفاع', null=True, upload_to=blog.models.upload_image_path, verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumb_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='ابعاد تصویر 80 در 80 ', null=True, upload_to=blog.models.upload_image_path, verbose_name='تصویر بند انگشتی'),
        ),
    ]
