# Generated by Django 5.0.6 on 2025-06-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_image_alter_post_thumb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_link_allowed',
            field=models.BooleanField(default=False, verbose_name='وضعیت ساخت لینک داخلی'),
        ),
    ]
