# Generated by Django 5.0.6 on 2025-06-26 13:42

import blog.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_create_link_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb_image',
            field=imagekit.models.fields.ProcessedImageField(help_text='ابعاد تصویر 80 در 80 ', null=True, upload_to=blog.models.upload_image_path, verbose_name='تصویر بند انگشتی'),
        ),
    ]
