# Generated by Django 5.0.6 on 2024-09-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financials',
            name='tax',
            field=models.FloatField(default=10, verbose_name='مالیات بر ارزش افزوده'),
        ),
    ]
