# Generated by Django 5.0.6 on 2024-09-24 07:05

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_financials_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juridical_personality_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان شخصیت حقوقی')),
                ('juridical_personality_address', models.TextField(blank=True, null=True, verbose_name='آذرس شخصیت حقوقی')),
                ('economic_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='کد اقتصادی')),
                ('national_id', models.CharField(blank=True, max_length=12, null=True, verbose_name='شناسه ملی')),
                ('national_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='کد ملی')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('firm_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='شماره ثبت')),
                ('tel_no', models.CharField(max_length=150, null=True, verbose_name='شماره تماس')),
                ('signature', models.ImageField(upload_to=settings.models.upload_image_setting_path, verbose_name='تصویر امضاء')),
                ('has_official_bill', models.BooleanField(default=False, verbose_name='وضعیت ارائه فاکتور رسمی')),
            ],
            options={
                'verbose_name': 'اطلاعات شرکت',
                'verbose_name_plural': 'اطلاعات شرکت',
            },
        ),
    ]
