# Generated by Django 5.0.6 on 2024-09-24 12:27

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=150, verbose_name='عنوان فروشگاه')),
                ('brand_name', models.CharField(max_length=50, verbose_name='عنوان برند')),
                ('siteUrl', models.URLField(blank=True, max_length=250, null=True, verbose_name='آدرس سایت')),
                ('opt_time', models.IntegerField(default=0, help_text='یه ثانیه باشد', verbose_name='زمان انقضای کد تایید')),
                ('order_cancel_time', models.IntegerField(default=360, verbose_name='مهلت پرداخت سفارش')),
                ('order_contraction_cancel_time', models.IntegerField(default=86400, verbose_name='مهلت پرداخت مبلغ پیش پرداخت در خرید اقساطی')),
                ('brand_logo', models.ImageField(upload_to=settings.models.upload_image_setting_path, verbose_name='لوگوی سایت')),
                ('header_event_baner', models.ImageField(null=True, upload_to=settings.models.upload_image_setting_path, verbose_name='بنر مناسبت در هدر')),
                ('site_slogan', models.CharField(max_length=250, null=True, verbose_name='شعار فروشگاه')),
                ('site_description', models.TextField(max_length=500, null=True, verbose_name='توضیحات کوتاه سایت')),
                ('work_time_text', models.TextField(max_length=500, null=True, verbose_name='متن ساعات کاری فروشگاه ')),
                ('copy_right_text', models.TextField(max_length=500, null=True, verbose_name='متن کپی رایت ')),
                ('link_instagram', models.URLField(blank=True, max_length=250, null=True, verbose_name='لینک اینستاگرام')),
                ('link_telegram', models.URLField(blank=True, max_length=250, null=True, verbose_name='لینک تلگرام')),
                ('link_facebook', models.URLField(blank=True, max_length=250, null=True, verbose_name='لینک واتس اپ')),
                ('link_twitter', models.URLField(blank=True, max_length=250, null=True, verbose_name='لینک تویتر')),
                ('shop_address', models.TextField(max_length=500, null=True, verbose_name='آدرس فروشگاه')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='آدرس ایمیل')),
                ('share_product_text', models.TextField(max_length=500, null=True, verbose_name='متن اشتراک گذاری لینک محصول')),
                ('whatsapp_share', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک ارسال پیام توسط واتس اپ')),
                ('telegram_share', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک ارسال پیام توسط تلگرام')),
                ('twitter_share', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک ارسال پیام توسط توییتر')),
                ('facebook_share', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک ارسال پیام توسط فیسبوک')),
            ],
            options={
                'verbose_name': 'تظیمات',
                'verbose_name_plural': 'تظیمات عمومی',
            },
        ),
        migrations.CreateModel(
            name='SMSSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان وب سرویس')),
                ('api_type', models.CharField(choices=[('MELIPAYAMAR', 'ملی پیامک'), ('RAZPAYAMAK', 'راز پیامک'), ('None', 'تنظیم نشده')], default='None', max_length=50, verbose_name='وب سرویس')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('code_cancel', models.IntegerField(default=1, verbose_name='کد متن مهلت پرداخت سفارش')),
                ('cancel_order_is_active', models.BooleanField(default=True, verbose_name='وضعیت ارسال پیامک مهلت پرداخت')),
                ('code_otp', models.IntegerField(default=1, verbose_name='کد متن کد یک بار مصرف')),
                ('code_pending_payment', models.IntegerField(default=1, verbose_name='کد متن پیامک در انتظار پرداخت')),
                ('pending_payment_is_active', models.BooleanField(default=True, verbose_name='وضعیت ارسال پیامک در انتظار پرداخت')),
                ('code_completed_payment', models.IntegerField(default=1, verbose_name='کد متن پیامک در تکمیل شدن پرداخت')),
                ('completed_payment_is_active', models.BooleanField(default=True, verbose_name='وضعیت ارسال پیامک در تکمیل شدن پرداخت')),
                ('code_deposit_completed_payment', models.IntegerField(default=1, verbose_name='کد متن پیامک در تکمیل شدن پیش پرداخت')),
                ('deposit_completed_payment_is_active', models.BooleanField(default=True, verbose_name='وضعیت ارسال پیامک در تکمیل شدن  پیش پرداخت')),
                ('username', models.CharField(blank=True, max_length=250, null=True, verbose_name='نام کاربری')),
                ('password', models.CharField(blank=True, max_length=250, null=True, verbose_name='رمز عبور')),
                ('api_link', models.URLField(blank=True, null=True, verbose_name='لینک وب سرویس')),
            ],
            options={
                'verbose_name': 'تنظیمات پیامک',
                'verbose_name_plural': 'تنظیمات پیامک',
            },
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='warehouse_address',
            field=models.TextField(blank=True, null=True, verbose_name='آذرس شخصیت حقوقی'),
        ),
    ]
