# Generated by Django 5.0.6 on 2024-09-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_setting_smssetting_companyinfo_warehouse_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='national_code',
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='warehouse_address',
            field=models.TextField(blank=True, null=True, verbose_name='آذرس انبار'),
        ),
    ]
