# Generated by Django 5.0.6 on 2024-10-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_remove_companyinfo_national_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='share_product_text',
        ),
        migrations.AddField(
            model_name='setting',
            name='first_page_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات صفحه اول'),
        ),
        migrations.AddField(
            model_name='setting',
            name='first_page_tag_line',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='شعار صفحه اول'),
        ),
    ]
