# Generated by Django 5.0.6 on 2024-10-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_remove_setting_share_product_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='shop_address',
        ),
        migrations.AddField(
            model_name='setting',
            name='address',
            field=models.TextField(max_length=500, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='setting',
            name='tel_no',
            field=models.CharField(max_length=150, null=True, verbose_name='شماره تماس'),
        ),
    ]
