# Generated by Django 5.0.6 on 2024-10-08 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_page_create_link_allowed'),
        ('settings', '0007_remove_setting_shop_address_setting_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='about_us_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.page', verbose_name='صفحه تمام با ما'),
        ),
    ]
