# Generated by Django 5.0.6 on 2024-10-09 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_page_is_main_page'),
        ('settings', '0008_setting_about_us_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='main_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_page', to='pages.page', verbose_name='صفحه اصلی'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_us_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_us_page', to='pages.page', verbose_name='صفحه تمام با ما'),
        ),
    ]
