# Generated by Django 5.0.6 on 2024-10-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_setting_main_page_alter_setting_about_us_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='facebook_share',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک فیسبوک'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='telegram_share',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='twitter_share',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک توییتر'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='whatsapp_share',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک واتس اپ'),
        ),
    ]
