# Generated by Django 5.0.6 on 2024-10-11 07:28

import settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_setting_facebook_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='brand_logo',
            field=models.FileField(upload_to=settings.models.upload_image_setting_path, verbose_name='لوگوی سایت'),
        ),
    ]
