# Generated by Django 5.0.6 on 2024-10-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_alter_setting_brand_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='header_event_baner',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_facebook',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_instagram',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_telegram',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_twitter',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='order_contraction_cancel_time',
        ),
    ]
