# Generated by Django 5.0.6 on 2024-11-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_remove_setting_header_event_baner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک فیسبوک'),
        ),
        migrations.AddField(
            model_name='setting',
            name='telegram_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AddField(
            model_name='setting',
            name='twitter_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک توییتر'),
        ),
        migrations.AddField(
            model_name='setting',
            name='whatsapp_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک واتس اپ'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='facebook_share',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک ارسال پیام توسط فیسبوک'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='telegram_share',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک ارسال پیام توسط تلگرام'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='twitter_share',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک ارسال پیام توسط توییتر'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='whatsapp_share',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک ارسال پیام توسط واتس اپ'),
        ),
    ]
