# Generated by Django 5.0.6 on 2024-11-08 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_setting_facebook_link_setting_telegram_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='facebook_share',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='telegram_share',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='twitter_share',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='whatsapp_share',
        ),
    ]
