# Generated by Django 5.0.6 on 2024-11-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_remove_setting_facebook_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک اینستاگرام'),
        ),
    ]
