# Generated by Django 5.0.6 on 2024-11-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_setting_instagram_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('slug', models.SlugField(null=True, verbose_name='نامک')),
                ('code', models.TextField(blank=True, null=True, verbose_name='اسکریپت')),
                ('type', models.CharField(blank=True, choices=[('symbol', 'نماد'), ('tag', 'تگ')], max_length=50, null=True, verbose_name='نوع')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('location', models.CharField(blank=True, choices=[('header', 'هدر'), ('footer', 'فوتر')], max_length=50, null=True, verbose_name='جانمایی کدک')),
                ('location_order', models.IntegerField(default=1, verbose_name='ترتیب قرار گرفتن')),
            ],
            options={
                'verbose_name': 'کدک',
                'verbose_name_plural': 'کدکها',
            },
        ),
    ]
