# Generated by Django 5.0.6 on 2024-11-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_jscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='keywords',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='کلمات کلیدی صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='setting',
            name='meta_desc',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='توضیحات سئو صفحه اصلی'),
        ),
        migrations.AddField(
            model_name='setting',
            name='meta_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='عنوان سئو صفحه اصلی'),
        ),
    ]
