# Generated by Django 5.0.6 on 2024-11-15 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_emails_product'),
        ('settings', '0017_setting_keywords_setting_meta_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='about_us_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_us_page', to='pages.page', verbose_name='صفحه تماس با ما'),
        ),
    ]
