# Generated by Django 5.0.6 on 2024-12-13 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_productinventory_after_discount_and_more'),
        ('settings', '0018_alter_setting_about_us_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='default_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.attribute', verbose_name='ویژگی پیش فرض در مرتب سازی محصولات'),
        ),
    ]
