# Generated by Django 5.0.6 on 2024-12-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_setting_default_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='default_attribute',
        ),
    ]
