# Generated by Django 5.0.6 on 2024-12-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_remove_setting_default_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='whatsapp_num',
            field=models.CharField(max_length=150, null=True, verbose_name='شماره واتس اپ'),
        ),
    ]
