# Generated by Django 5.0.6 on 2025-04-27 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_emails_email'),
        ('settings', '0021_setting_whatsapp_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='terms_conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_condition_page', to='pages.page', verbose_name='صفحه قوانین'),
        ),
    ]
