# Generated by Django 5.0.6 on 2025-06-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_setting_terms_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='category_link_task_run_time',
            field=models.IntegerField(default=1000, verbose_name='فاصله زمانی اجرای متد لینک ساز داخلی دسته بندی ها'),
        ),
        migrations.AddField(
            model_name='setting',
            name='create_internal_link_task',
            field=models.BooleanField(default=True, verbose_name='وضعیت تسک لینک ساز داخلی'),
        ),
        migrations.AddField(
            model_name='setting',
            name='page_internal_link_task_run_time',
            field=models.IntegerField(default=1000, verbose_name='فاصله زمانی اجرای متد لینک ساز داخلی صفحه هات'),
        ),
        migrations.AddField(
            model_name='setting',
            name='post_internal_link_task_run_time',
            field=models.IntegerField(default=1000, verbose_name='فاصله زمانی اجرای متد لینک ساز داخلی نوشته ها'),
        ),
        migrations.AddField(
            model_name='setting',
            name='product_internal_link_task_run_time',
            field=models.IntegerField(default=1000, verbose_name='فاصله زمانی اجرای متد لینک ساز داخلی محصولات'),
        ),
    ]
