# Generated by Django 5.0.6 on 2025-07-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_setting_category_link_task_run_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='clear_cache',
            field=models.BooleanField(default=False, verbose_name='پاک کردن کش سایت'),
        ),
    ]
