# Generated by Django 5.0.6 on 2025-07-06 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_contact_remove_contactus_is_english_form_and_more'),
        ('settings', '0024_setting_clear_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contact_us_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_us_page', to='pages.page', verbose_name='صفحه تماس با ما'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_us_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_us_page', to='pages.page', verbose_name='صفحه درباره ما'),
        ),
    ]
