# Generated by Django 5.0.6 on 2025-07-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0025_setting_contact_us_page_alter_setting_about_us_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='tel_no2',
            field=models.CharField(max_length=150, null=True, verbose_name='شماره تماس 2'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='tel_no',
            field=models.CharField(max_length=150, null=True, verbose_name='شماره تماس 1'),
        ),
    ]
