# Generated by Django 5.0.6 on 2025-07-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0026_setting_tel_no2_alter_setting_tel_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='tel_no2',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='شماره تماس 2'),
        ),
    ]
