# Generated by Django 5.0.6 on 2025-07-06 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_page_use_content_jinja_page_contact_form'),
        ('settings', '0027_alter_setting_tel_no2'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contact_us_en_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_us_en_page', to='pages.page', verbose_name='صفحه تماس با ما - انگلیسی'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact_us_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_us_page', to='pages.page', verbose_name='صفحه تماس با ما- فارسی'),
        ),
    ]
