# Generated by Django 5.0.6 on 2025-07-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_setting_contact_us_en_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='en_address',
            field=models.TextField(max_length=500, null=True, verbose_name='آدرس انگلیسی'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.TextField(max_length=500, null=True, verbose_name='آدرس فارسی'),
        ),
    ]
