# Generated by Django 5.0.6 on 2025-07-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_setting_en_address_alter_setting_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='mobile',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='موبایل'),
        ),
    ]
