# Generated by Django 5.0.6 on 2024-07-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'حساب کاربر', 'verbose_name_plural': 'حساب کاربران'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_mobile',
        ),
    ]
