# Generated by Django 5.0.6 on 2024-07-15 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_account', '0002_alter_user_options_remove_user_new_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='فرمت شماره موبایل اشتباه است.', regex='^09\\d{9}$')], verbose_name='شماره موبایل'),
        ),
    ]
