# Generated by Django 5.0.6 on 2024-07-15 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_account', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='یک آدرس ایمیل معتبر وارد نمایید.')], verbose_name='آدرس ایمیل'),
        ),
    ]
