# Generated by Django 5.0.6 on 2024-07-16 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_account', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(default=datetime.datetime(2024, 7, 16, 6, 40, 55, 123687, tzinfo=datetime.timezone.utc), max_length=100, verbose_name='کد فعالسازی ایمیل'),
            preserve_default=False,
        ),
    ]
