# Generated by Django 5.0.6 on 2024-09-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_account', '0007_alter_user_email_active_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس منزل'),
        ),
    ]
