# Generated by Django 5.0.6 on 2024-09-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_account', '0008_user_personal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_official',
            field=models.BooleanField(default=False, verbose_name='کاربر شخصیت حقوقی است'),
        ),
    ]
