# Generated by Django 5.0.6 on 2024-09-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_account', '0009_user_is_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='official_address',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='آدرس حقوقی'),
        ),
    ]
