# Generated by Django 5.0.6 on 2024-09-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_account', '0010_user_official_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firm_tel_no',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره تماس حقوقی'),
        ),
    ]
