# Generated by Django 5.0.6 on 2024-09-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_account', '0011_user_firm_tel_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_order_invoice',
            field=models.BooleanField(default=False, verbose_name='نمایش فاکتور مشتریان'),
        ),
    ]
