# Generated by Django 5.0.6 on 2024-09-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_account', '0012_user_has_order_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='official_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
    ]
