# Generated by Django 5.0.6 on 2024-09-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_account', '0013_user_official_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firm_economical_no',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شناسه ملی شرکت'),
        ),
    ]
