# Generated by Django 5.0.6 on 2024-11-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_account', '0014_alter_user_firm_economical_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='official_address',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='آدرس حقوقی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_address',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='آدرس منزل'),
        ),
    ]
