# Generated by Django 5.0.6 on 2024-11-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_account', '0015_user_national_code_alter_user_official_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی شخصیت حقیقی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='official_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی شخصیت حقوقی'),
        ),
    ]
