# Generated by Django 5.0.6 on 2024-10-07 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        ('product', '0023_alter_productinventory_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فهرست')),
            ],
            options={
                'verbose_name': 'فهرست',
                'verbose_name_plural': 'فهرستها',
            },
        ),
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('icon', models.CharField(blank=True, max_length=200, null=True, verbose_name='آیکن')),
                ('type', models.IntegerField(choices=[(1, 'دسته بندی محصولات'), (2, 'نوشته ها'), (3, 'برگه ها'), (4, 'لینک دخواه')], default=1, verbose_name='نوع منو')),
                ('display_order', models.IntegerField(default=1, verbose_name='اولویت نمایش')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر')),
                ('url', models.URLField(blank=True, null=True, verbose_name='ادرس صفحه')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu', verbose_name='نام فهرست')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='نام برگه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_menus', to='menus.menulist', verbose_name='منو مادر')),
                ('product_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productscats', verbose_name='گروه محصول')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'ایتمها',
            },
        ),
        migrations.CreateModel(
            name='ProductCatMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'دسته بندی'), (2, 'دسته بندی برند'), (3, 'تگ محصول'), (4, 'لینک دلخواه')], default=1, verbose_name='نوع لینک')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('display_order', models.IntegerField(default=1, verbose_name='اولویت نمایش')),
                ('custom_link', models.URLField(blank=True, null=True, verbose_name='لینک دلخواه')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.productscats', verbose_name='دسته بندی')),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='menus.productcatmenu', verbose_name='دسته بندی مادر در منو')),
            ],
            options={
                'verbose_name': 'آیتم های منو',
                'verbose_name_plural': 'منوی دسته بندی کالا',
            },
        ),
    ]
