# Generated by Django 5.0.6 on 2024-10-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulist',
            name='product_cat',
        ),
        migrations.AlterField(
            model_name='menulist',
            name='type',
            field=models.IntegerField(choices=[(2, 'نوشته ها'), (3, 'برگه ها'), (4, 'لینک دخواه')], default=1, verbose_name='نوع منو'),
        ),
        migrations.AlterField(
            model_name='productcatmenu',
            name='type',
            field=models.IntegerField(choices=[(1, 'دسته بندی'), (3, 'تگ محصول'), (4, 'لینک دلخواه')], default=1, verbose_name='نوع لینک'),
        ),
    ]
