# Generated by Django 5.0.6 on 2024-10-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_remove_menulist_product_cat_alter_menulist_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulist',
            name='page',
        ),
    ]
