# Generated by Django 5.0.6 on 2024-10-08 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_remove_menulist_page'),
        ('pages', '0005_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulist',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='نام برگه'),
        ),
    ]
