# Generated by Django 5.0.6 on 2024-10-11 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_menulist_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulist',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='menulist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menulist',
            name='page',
        ),
        migrations.RemoveField(
            model_name='menulist',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='menulist',
            name='type',
        ),
        migrations.AlterField(
            model_name='menulist',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menu', verbose_name='فهرست'),
        ),
    ]
