# Generated by Django 5.0.6 on 2024-10-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_remove_menulist_icon_remove_menulist_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'فهرست فوتر', 'verbose_name_plural': 'فهرستهای فوتر'},
        ),
        migrations.AddField(
            model_name='menu',
            name='display_order',
            field=models.IntegerField(default=1, verbose_name='اولویت نمایش'),
        ),
    ]
