# Generated by Django 5.0.6 on 2024-07-07 07:02

import components.models
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='عنوان slider در url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
        ),
        migrations.CreateModel(
            name='SliderSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('image_alt', models.CharField(max_length=250, null=True, verbose_name='متن جایگزین تصویر')),
                ('image_tooltip', models.CharField(max_length=250, null=True, verbose_name='نام تصویر')),
                ('link', models.URLField(blank=True, max_length=250, null=True, verbose_name='لینک صفحه فرود')),
                ('original_image', imagekit.models.fields.ProcessedImageField(upload_to=components.models.upload_original_image_web_path, verbose_name='لینک تصویر webp')),
                ('image_webp', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=components.models.upload_image_web_path, verbose_name='لینک تصویر webp')),
                ('is_origin_image', models.BooleanField(default=False, verbose_name='از تصویر اصلی استفاده شود')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('slider', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='components.slider', verbose_name='اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
                'ordering': ['display_order'],
            },
        ),
    ]
