# Generated by Django 5.0.6 on 2024-09-13 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0011_productmainfeature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_no', models.PositiveIntegerField(default=0, verbose_name='شماره فاکتور سیستم حسابداری')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی تحویل گیرنده')),
                ('mobile', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('connected', models.BooleanField(default=False, verbose_name='وضعیت تماس')),
                ('full_address', models.TextField(blank=True, max_length=1000, null=True, verbose_name='آدرس کامل')),
                ('is_for_next_bying', models.BooleanField(default=False, verbose_name='خرید بعدی')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='وضعیت ثبت سفارش')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('payed', models.BooleanField(default=False, verbose_name='وضعیت پرداخت از درگاه')),
                ('tax', models.FloatField(default=9, verbose_name='مالیات و عوارض')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='وضعیت لغو سفارش')),
                ('payment_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='نحوه پرداخت')),
                ('total_shipping_cost', models.FloatField(default=0, verbose_name='هزینه حمل')),
                ('status', models.CharField(blank=True, max_length=150, null=True, verbose_name='وضعیت سفارش')),
                ('status_id', models.PositiveIntegerField()),
                ('confirm', models.BooleanField(default=False, verbose_name='وضعیت ارسال سفارشات به انبار')),
                ('order_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات سفارش')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ای پی کاربر')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('old_referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_aff_referee', to=settings.AUTH_USER_MODEL, verbose_name='معرف قبلی')),
                ('referee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aff_referee', to=settings.AUTH_USER_MODEL, verbose_name='معرف')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت سفارش')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام کامل')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام خانوادگی')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='موبایل')),
                ('is_official', models.BooleanField(default=False, verbose_name='شخصیت حقوقی')),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام سازمان')),
                ('firm_no', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره ثبت')),
                ('firm_national_id', models.CharField(blank=True, max_length=11, null=True, verbose_name='شناسه ملی')),
                ('firm_economical_no', models.CharField(blank=True, max_length=12, null=True, verbose_name='کد اقتصادی')),
                ('full_address', models.TextField(blank=True, max_length=700, null=True, verbose_name='آدرس کامل')),
                ('tel_no', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره تماس')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.FloatField(default=0, verbose_name='مبلغ')),
                ('supplement_price', models.FloatField(default=0, verbose_name='قیمت تامین')),
                ('margin_percentage', models.DecimalField(decimal_places=1, default=6, max_digits=3, verbose_name='درصد سود')),
                ('gift_percentage', models.DecimalField(decimal_places=1, default=80, help_text='برای کالاهای لحاظ می شود که قیمت فروش بالاتر از حاشیه سود است ', max_digits=3, verbose_name='درصد مبلغ هدیه از حاشیه سود')),
                ('loan_base_price', models.FloatField(default=0, verbose_name='مبلغ پایه وام')),
                ('item', models.CharField(max_length=500, verbose_name='آیتم سفارش')),
                ('total_discount', models.FloatField(default=0, verbose_name='تخفیف کل')),
                ('product_count', models.PositiveIntegerField(verbose_name='تعداد')),
                ('is_not_canceled', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('has_refund_percentage', models.BooleanField(default=False, verbose_name='از بهره ایتم استفاده شود')),
                ('refund_percentage', models.FloatField(default=0, verbose_name='درصد بهره در طول دوره اقساط')),
                ('prepayment_percentage', models.FloatField(default=0, verbose_name='درصد پیش پرداخت')),
                ('gift', models.FloatField(default=0, verbose_name='مبلغ هدیه')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitem', to='orders.order', verbose_name='شماره سفارش')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.productinventory', verbose_name='نام محصول')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتمهای سفارشات',
                'ordering': ('-id',),
            },
        ),
    ]
