# Generated by Django 5.0.6 on 2024-09-13 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOtherPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت')),
                ('payment_memo', models.CharField(blank=True, max_length=250, null=True, verbose_name='توضیحات پرداخت')),
                ('amount', models.FloatField(default=0, verbose_name='مبلغ پرداختی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'پرداختی سفارش',
                'verbose_name_plural': 'سایر پرداختیهای سفارش',
            },
        ),
    ]
