# Generated by Django 5.0.6 on 2024-09-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderotherpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='gift_percentage',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='has_refund_percentage',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='loan_base_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='margin_percentage',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='prepayment_percentage',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='refund_percentage',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax',
            field=models.FloatField(default=0, verbose_name='مالیات بر ارزش افزوده'),
        ),
    ]
