# Generated by Django 5.0.6 on 2024-09-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_gift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_for_next_bying',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='referee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AlterField(
            model_name='order',
            name='status_id',
            field=models.PositiveIntegerField(choices=[(0, 'سبد خرید'), (1, 'در انتظار پرداخت'), (2, 'پرداخت شده'), (3, 'پیش پرداخت'), (4, 'لغو شده')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=9, verbose_name='درصد مالیات بر ارزش افزوده'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_discount',
            field=models.FloatField(default=0, verbose_name='تخفیف'),
        ),
    ]
