# Generated by Django 5.0.6 on 2024-09-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_is_canceled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_id',
            field=models.CharField(choices=[('0', 'سبد خرید'), ('1', 'در انتظار پرداخت'), ('2', 'پرداخت شده'), ('3', 'پیش پرداخت'), ('4', 'لغو شده')], default='0', max_length=10, verbose_name='وضعیت'),
        ),
    ]
