# Generated by Django 5.0.6 on 2024-09-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='connected',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='order',
            name='old_referrer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_ip',
        ),
    ]
