# Generated by Django 5.0.6 on 2024-11-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_connected_remove_order_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد واحد'),
        ),
    ]
