# Generated by Django 5.0.6 on 2024-12-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_unit_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_discount',
            field=models.FloatField(default=0, verbose_name='تخفیف به هر واحد'),
        ),
    ]
