# Generated by Django 5.0.6 on 2025-06-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JuiceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='کلمه کلیدی')),
                ('link', models.URLField(max_length=2000, verbose_name='لینک')),
                ('prirority', models.IntegerField(default=0, verbose_name='اولویت')),
                ('authorized_tags', models.TextField(help_text='تگها را با , از همدیگر جدا کنید', verbose_name='تگهایی مجاز')),
                ('apply_for_posts', models.BooleanField(default=False, verbose_name='برای نوشته ها اعمال گردد')),
                ('apply_for_products', models.BooleanField(default=False, verbose_name='برای توضیحات محصولات اعمال گردد')),
                ('apply_for_pages', models.BooleanField(default=False, verbose_name='برای صفحه هات اعمال گردد')),
                ('apply_for_categories', models.BooleanField(default=False, verbose_name='برای دسته بندی محصولات اعمال گردد')),
            ],
            options={
                'verbose_name': 'لینک داخلی',
                'verbose_name_plural': 'لینکهای داخلی',
                'ordering': ['prirority'],
            },
        ),
    ]
