# Generated by Django 5.0.6 on 2025-09-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juicelink',
            name='no_fallow',
            field=models.BooleanField(default=False, verbose_name='نو فالو شود'),
        ),
    ]
